version: '3.8'

services:
  backtester:
    build: .
    container_name: backtester
    ports:
      - "3000:3000"
    networks:
      - exxa_network
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: ["bun", "--watch", "run", "./src/api/index.ts"]

  migrations:
    build: .
    container_name: migrations
    depends_on:
      database:
        condition: service_healthy
    networks:
      - exxa_network
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: ["bun", "run", "migrate:latest"]

  database:
    image: 'postgres:16.4-alpine3.20'
    container_name: backtester_db
    ports:
      - 5432:5432
    networks:
      - exxa_network
    environment:
        PGPASSWORD: '${DB_PASS}'
        POSTGRES_DB: '${DB_NAME}'
        POSTGRES_USER: '${DB_USER}'
        POSTGRES_PASSWORD: '${DB_PASS}'
    volumes:
        - 'db:/var/lib/postgresql/data'
    env_file:
      - .env
    healthcheck:
        test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
        interval: 1s
        timeout: 1s
        retries: 10

networks:
  exxa_network:
    name: exxa

volumes:
  db:
    driver: local