version: '3.8'

services:
  exxahub_loadtester:
    build: loadtest/
    container_name: exxahub_loadtester
    networks:
      - exxahub_network
    volumes:
      - ./loadtest/test.js:/app/test.js
    working_dir: /app